server:
  port: 10050
spring:
  application:
    name: service-common
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      config:
        namespace: 36bb4e11-653f-4379-ba11-01b573f2b6c6
      discovery:
        namespace: 36bb4e11-653f-4379-ba11-01b573f2b6c6
  config:
    import:
      - nacos:${spring.application.name}.yml
  # 单机redis配置（归属到spring节点下，是核心修正点）
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      # password: root
      jedis:
        pool:
          min-idle: 2
          max-idle: 10
# 短信配置（顶级节点，缩进正确）
sms:
  accessKeyId: LTAI5tBMMMn9GnHUkb7Zyf5z
  accessKeySecret: mYOhkB0yWdlx3Tj01Q44dBgPc5hxR4
  signName: 速通互联验证码
  templateCode: 100001

# ------------------- 以下是注释的集群/哨兵配置（仅作参考，无需启用） -------------------
# redis高可用集群的客户端连接配置
#spring:
#  data:
#    redis:
#      cluster:
#        nodes: 127.0.0.1:6379,127.0.0.1:6380  #配置整个高可用集群半数以上的节点数。
#      password: root
# 哨兵模式的客户端连接配置
#spring:
#  data:
#    redis:
#      sentinel:
#        master: mymaster   #哨兵配置时，sentinel monitor mymaster 127.0.0.1 6380 1
#        nodes: 127.0.0.1:26379  #哨兵节点ip：port
#      password: root #主从节点的连接密码

rocketmq:
  name-server: 127.0.0.1:9876 #nameserver地址
  # 是否开启自动配置
  producer:
    # 发送同一类消息设置为同一个group，保证唯一默认不需要设置，rocketmq会使用ip@pid（pid代表jvm名字）作为唯一标识
    group: "commons-service-producer"
    # 消息最大长度 默认 1024 * 4 (4M)
    max-message-size: 4096
    # 发送消息超时时间，默认 3000
    send-message-timeout: 3000
    # 发送消息失败重试次数，默认2
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 2